name: automerge-dependabot-pr

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - id: ci
        uses: the-actions-org/workflow-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yaml
          wait-for-completion: true
          wait-for-completion-interval: 30s
          ref: ${{ github.event.pull_request.head.ref }}

      - if: ${{ steps.ci.outputs.workflow-conclusion }} == 'success'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            As the tests have succeeded, I will merge this PR.

      - if: ${{ steps.ci.outputs.workflow-conclusion }} == 'success'
        run: |
          curl -X PUT \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"merge_method":"merge"}' \
            "https://api.github.com/repos/enuesaa/kakkofn/pulls/$PR_NUMBER/merge"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
