name: automerge-dependabot-pr

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  automerge:
    # if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - id: ci
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: ci.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-completion: true

      - run: |
          echo "${{ steps.ci.outputs }}";

      - if: ${{ steps.ci.outputs.workflow-conclusion }} == 'success'
        run: echo a

      # - run: |
      #     curl -X PUT \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       -H "Authorization: Bearer $GITHUB_TOKEN" \
      #       "https://api.github.com/repos/enuesaa/kakkofn/pulls/$PR_NUMBER/merge" \
      #       -d '{"merge_method":"merge"}'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PR_NUMBER: ${{ github.event.pull_request.number }}
