name: e2e

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - uses: pnpm/action-setup@v2
        with:
          version: '9'

      - uses: actions/cache@v4
        with:
          key: ${{ hashFiles('e2e/pnpm-lock.yaml') }}
          path: |
            e2e/node_modules
            /home/runner/.cache/ms-playwright

      - run: pnpm install
      - run: pnpm pw:init

      # always mark success because this test aims to extract visual diffs.
      - run: pnpm pw:test || true

      - uses: actions/upload-artifact@v4
        with:
          name: report
          path: e2e/pw-report
          retention-days: 1

      - uses: daun/playwright-report-summary@v3
        with:
          report-file: e2e/pw-results/results.json
          job-summary: true
