name: e2e

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - uses: pnpm/action-setup@v2
        with:
          version: '9'
      
      - run: pnpm install

      - working-directory: e2e
        run: pnpm install
      - working-directory: e2e
        run: pnpm pw:init
      
      # always mark success because this test aims to extract visual diffs.
      - working-directory: e2e
        run: pnpm pw:test || true

      - uses: actions/upload-artifact@v4
        with:
          name: report
          path: e2e/pw-report
          retention-days: 1
