name: e2e

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - uses: pnpm/action-setup@v2
        with:
          version: '9'

      - working-directory: e2e
        run: pnpm install
      - working-directory: e2e
        run: pnpm pw:install
      - working-directory: e2e
        run: pnpm pw:test
